export const CREATE_NEW_ORDER = 'ORDERS::CREATE_NEW_ORDER';
export const UPDATE_ORDER_CONTENT = 'ORDERS::UPDATE_ORDER_CONTENT';
export const UPDATE_ORDER_STATUS = 'ORDERS::UPDATE_ORDER_STATUS';
export const FORM_SUBMIT_SUCCEEDED = 'ORDERS::FORM_SUBMIT_SUCCEEDED';
export const FORM_SUBMIT_FAILED = 'ORDERS::FORM_SUBMIT_FAILED';
export const GET_ORDERS = 'ORDERS::GET_ORDERS';
export const INSERT_ORDERS = 'ORDERS::INSERT_ORDERS';
